package openvpn

import (
	"bytes"
	"encoding/hex"
	"encoding/pem"
	"errors"
	"fmt"
	"net"
	"strconv"
	"strings"
)

const (
	ProtoUDP = "udp"
	ProtoTCP = "tcp"

	CipherAES128GCM        = "AES-128-GCM"
	CipherAES192GCM        = "AES-192-GCM"
	CipherAES256GCM        = "AES-256-GCM"
	CipherAESCBC           = "AES-CBC"
	CipherAES128CBC        = "AES-128-CBC"
	CipherAES192CBC        = "AES-192-CBC"
	CipherAES256CBC        = "AES-256-CBC"
	CipherChaCha20Poly1305 = "CHACHA20-POLY1305"
	AuthMD5                = "MD5"
	AuthSHA1               = "SHA1"
	AuthSHA256             = "SHA256"
	AuthSHA384             = "SHA384"
	AuthSHA512             = "SHA512"

	CompLzoYes = "yes"

	CompressionNone      = ""
	CompressionStub      = "stub"
	CompressionStubV2    = "stub-v2"
	CompressionCompLZONo = "comp-lzo"
	CompressionCompLZO   = "comp-lzo yes"
)

// ClientConfig is the normalized subset generated by hwdsl2/openvpn-install.
type ClientConfig struct {
	RemoteHost string
	RemotePort uint16
	Proto      string
	Dev        string
	Cipher     string
	Auth       string
	CompLZO    string

	CA       []byte
	Cert     []byte
	Key      []byte
	TLSCrypt []byte
	TLSAuth  []byte

	Username    string
	Password    string
	Compression string

	TLSCryptKey  []byte
	TLSAuthKey   []byte
	KeyDirection string
}

// DataCipherKeyLength returns the key size for the negotiated data cipher.
func (c ClientConfig) DataCipherKeyLength() int {
	switch c.Cipher {
	case CipherAES256GCM, CipherAES256CBC, CipherChaCha20Poly1305:
		return 32
	case CipherAES192GCM, CipherAES192CBC:
		return 24
	default:
		return 16
	}
}

func (c ClientConfig) RemoteAddress() string {
	return net.JoinHostPort(c.RemoteHost, strconv.Itoa(int(c.RemotePort)))
}

func normalizeProto(proto string) string {
	switch strings.ToLower(strings.TrimSpace(proto)) {
	case "":
		return ProtoUDP
	case "udp", "udp4":
		return ProtoUDP
	case "tcp", "tcp-client", "tcp4", "tcp4-client":
		return ProtoTCP
	default:
		return strings.ToLower(strings.TrimSpace(proto))
	}
}

func normalizeCipher(cipher string) string {
	switch strings.ToUpper(strings.TrimSpace(cipher)) {
	case "":
		return CipherAES128GCM
	case CipherAESCBC:
		return CipherAES128CBC
	default:
		return strings.ToUpper(strings.TrimSpace(cipher))
	}
}

func normalizeAuth(auth string) string {
	switch strings.ToUpper(strings.TrimSpace(auth)) {
	case "":
		return AuthSHA1
	case "SHA-1":
		return AuthSHA1
	default:
		return strings.ToUpper(strings.TrimSpace(auth))
	}
}

func normalizeCompLZO(compLZO string) string {
	switch strings.ToLower(strings.TrimSpace(compLZO)) {
	case "yes", "adaptive":
		return CompLzoYes
	default:
		return strings.ToLower(strings.TrimSpace(compLZO))
	}
}

func (c *ClientConfig) Prepare() error {
	if c == nil {
		return errors.New("nil openvpn client config")
	}
	c.RemoteHost = strings.TrimSpace(c.RemoteHost)
	c.Proto = normalizeProto(c.Proto)
	if c.Dev == "" {
		c.Dev = "tun"
	}
	c.Dev = strings.ToLower(strings.TrimSpace(c.Dev))
	c.Cipher = normalizeCipher(c.Cipher)
	c.Auth = normalizeAuth(c.Auth)
	c.CompLZO = normalizeCompLZO(c.CompLZO)
	c.KeyDirection = strings.TrimSpace(c.KeyDirection)
	if strings.TrimSpace(c.Compression) != "" {
		compression, err := NormalizeCompression(c.Compression)
		if err != nil {
			return err
		}
		c.Compression = compression
	} else {
		c.Compression = compressionFromCompLZO(c.CompLZO)
	}
	if err := c.ValidateInstallScriptSubset(); err != nil {
		return err
	}
	if len(bytes.TrimSpace(c.TLSCrypt)) > 0 {
		key, err := DecodeStaticKey(c.TLSCrypt)
		if err != nil {
			return fmt.Errorf("parse tls-crypt key: %w", err)
		}
		c.TLSCryptKey = key
	}
	if len(bytes.TrimSpace(c.TLSAuth)) > 0 {
		key, err := DecodeStaticKey(c.TLSAuth)
		if err != nil {
			return fmt.Errorf("parse tls-auth key: %w", err)
		}
		c.TLSAuthKey = key
	}
	return nil
}

func (c *ClientConfig) ValidateInstallScriptSubset() error {
	if c == nil {
		return errors.New("nil openvpn client config")
	}
	if c.RemoteHost == "" || c.RemotePort == 0 {
		return errors.New("openvpn config requires remote host and port")
	}
	if c.Dev != "tun" {
		return fmt.Errorf("unsupported openvpn dev %q: only dev tun is supported", c.Dev)
	}
	if c.Proto != ProtoUDP && c.Proto != ProtoTCP {
		return fmt.Errorf("unsupported openvpn proto %q: only udp and tcp are supported", c.Proto)
	}
	if c.Cipher != CipherAES128GCM && c.Cipher != CipherAES192GCM && c.Cipher != CipherAES256GCM && c.Cipher != CipherAES128CBC && c.Cipher != CipherAES192CBC && c.Cipher != CipherAES256CBC && c.Cipher != CipherChaCha20Poly1305 {
		return fmt.Errorf("unsupported openvpn cipher %q: only %s, %s, %s, %s, %s, %s and %s are supported", c.Cipher, CipherAES128GCM, CipherAES192GCM, CipherAES256GCM, CipherAES128CBC, CipherAES192CBC, CipherAES256CBC, CipherChaCha20Poly1305)
	}
	if c.Auth != AuthMD5 && c.Auth != AuthSHA1 && c.Auth != AuthSHA256 && c.Auth != AuthSHA384 && c.Auth != AuthSHA512 {
		return fmt.Errorf("unsupported openvpn auth %q: only %s, %s, %s, %s and %s are supported", c.Auth, AuthMD5, AuthSHA1, AuthSHA256, AuthSHA384, AuthSHA512)
	}
	if c.CompLZO != "" && c.CompLZO != CompLzoYes && c.CompLZO != "no" {
		return fmt.Errorf("unsupported openvpn comp-lzo %q: only yes, no and adaptive are supported", c.CompLZO)
	}
	if _, err := NormalizeCompression(c.Compression); err != nil {
		return err
	}
	for name, value := range map[string][]byte{
		"ca": c.CA,
	} {
		if len(bytes.TrimSpace(value)) == 0 {
			return fmt.Errorf("openvpn config requires inline <%s> block", name)
		}
	}
	hasTLSCrypt := len(bytes.TrimSpace(c.TLSCrypt)) > 0
	hasTLSAuth := len(bytes.TrimSpace(c.TLSAuth)) > 0
	if hasTLSCrypt == hasTLSAuth {
		return errors.New("openvpn config requires exactly one of inline <tls-crypt> or <tls-auth> block")
	}
	if hasTLSCrypt && c.KeyDirection != "" {
		return errors.New("openvpn key-direction is only valid with tls-auth")
	}
	if hasTLSAuth && c.KeyDirection != "" && c.KeyDirection != "0" && c.KeyDirection != "1" {
		return fmt.Errorf("unsupported openvpn key-direction %q: only 0 or 1 are supported", c.KeyDirection)
	}
	if block, _ := pem.Decode(c.CA); block == nil {
		return errors.New("inline <ca> block is not PEM")
	}
	hasCert := len(bytes.TrimSpace(c.Cert)) > 0 || len(bytes.TrimSpace(c.Key)) > 0
	if hasCert {
		if len(bytes.TrimSpace(c.Cert)) == 0 || len(bytes.TrimSpace(c.Key)) == 0 {
			return errors.New("openvpn cert and key must both be set when using client certificate auth")
		}
		if block, _ := pem.Decode(c.Cert); block == nil {
			return errors.New("inline <cert> block is not PEM")
		}
		if block, _ := pem.Decode(c.Key); block == nil {
			return errors.New("inline <key> block is not PEM")
		}
	} else if strings.TrimSpace(c.Username) == "" {
		return errors.New("openvpn requires either cert+key or username (auth-user-pass)")
	}
	return nil
}

func NormalizeCompression(compression string) (string, error) {
	normalized := strings.ToLower(strings.TrimSpace(compression))
	normalized = strings.Join(strings.Fields(normalized), " ")
	switch normalized {
	case "", "false", "no", "off", "none", "disabled", "nocomp":
		return CompressionNone, nil
	case "true", "yes", "on", "compress", "compress stub", "stub":
		return CompressionStub, nil
	case "compress stub-v2", "stub-v2":
		return CompressionStubV2, nil
	case "comp-lzo", "comp-lzo no", "compress lzo", "lzo":
		return CompressionCompLZONo, nil
	case "comp-lzo yes", "comp-lzo adaptive":
		return CompressionCompLZO, nil
	default:
		return "", fmt.Errorf("unsupported openvpn compression %q: only compress/stub, stub-v2, and comp-lzo framing are supported", compression)
	}
}

func (c ClientConfig) CompressionMode() string {
	if strings.TrimSpace(c.Compression) == "" && strings.TrimSpace(c.CompLZO) != "" {
		return compressionFromCompLZO(normalizeCompLZO(c.CompLZO))
	}
	compression, _ := NormalizeCompression(c.Compression)
	return compression
}

func compressionFromCompLZO(compLZO string) string {
	switch normalizeCompLZO(compLZO) {
	case CompLzoYes:
		return CompressionCompLZO
	case "no":
		return CompressionCompLZONo
	default:
		return CompressionNone
	}
}

func DecodeStaticKey(block []byte) ([]byte, error) {
	var hexLines []string
	for _, raw := range strings.Split(string(block), "\n") {
		line := strings.TrimSpace(raw)
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		if strings.HasPrefix(line, "-----BEGIN OpenVPN Static key") || strings.HasPrefix(line, "-----END OpenVPN Static key") {
			continue
		}
		hexLines = append(hexLines, line)
	}
	encoded := strings.Join(hexLines, "")
	key, err := hex.DecodeString(encoded)
	if err != nil {
		return nil, err
	}
	if len(key) != 256 {
		return nil, fmt.Errorf("invalid static key length %d, expected 256 bytes", len(key))
	}
	return key, nil
}
